// src/components/DistributionForm.tsx
import React, { useState } from "react";

type DistributionFormProps = {
    data: DistributionData;
    onChange: (data: DistributionData) => void;
};

function DistributionForm({ data, onChange }: DistributionFormProps) {
    const [distribution, setDistribution] = useState<DistributionName>(
        data.name ?? "exponential"
    );
    const [mean, setMean] = useState<{ mean: number }>(
        data.name !== "uniform"
            ? { mean: (data.mean as Mean).mean ?? 0 }
            : { mean: 0 }
    );
    const [uniformMean, setUniformMean] = useState<{
        a: number;
        b: number;
    }>(
        data.name === "uniform"
            ? {
                  a: (data.mean as UniformMean).a ?? 0,
                  b: (data.mean as UniformMean).b ?? 0,
              }
            : { a: 0, b: 0 }
    );

    const handleDistributionChange = (
        event: React.ChangeEvent<HTMLSelectElement>
    ) => {
        setDistribution(() => {
            const newDistribution = event.target.value as DistributionName;

            onChange({
                name: newDistribution,
                mean: newDistribution === "uniform" ? uniformMean : mean,
            });

            return newDistribution;
        });
    };

    return (
        <div className="grid">
            <label htmlFor="entry_distribution">
                Distribución
                <select
                    value={distribution}
                    name=""
                    id="entry_distribution"
                    onChange={handleDistributionChange}
                >
                    <option value="uniform">Uniforme</option>
                    <option value="exponential">Exponencial</option>
                    <option value="poisson">Poisson</option>
                </select>
            </label>
            {distribution === "uniform" ? (
                <>
                    <label htmlFor="">
                        a
                        <input
                            type="text"
                            name=""
                            id=""
                            value={uniformMean.a}
                            onChange={(e) => {
                                setUniformMean((prev) => {
                                    onChange({
                                        name: "uniform",
                                        mean: {
                                            a: Number(e.target.value),
                                            b: prev.b,
                                        },
                                    });

                                    return {
                                        ...prev,
                                        a: Number(e.target.value),
                                    };
                                });
                            }}
                        />
                    </label>
                    <label htmlFor="">
                        b
                        <input
                            type="text"
                            name=""
                            id=""
                            value={uniformMean.b}
                            onChange={(e) => {
                                setUniformMean((prev) => {
                                    onChange({
                                        name: "uniform",
                                        mean: {
                                            a: prev.a,
                                            b: Number(e.target.value),
                                        },
                                    });
                                    return {
                                        ...prev,
                                        b: Number(e.target.value),
                                    };
                                });
                            }}
                        />
                    </label>
                </>
            ) : (
                <label>
                    Media
                    <input
                        type="text"
                        name=""
                        id=""
                        value={mean.mean}
                        onChange={(e) => {
                            setMean((prev) => {
                                onChange({
                                    name: distribution,
                                    mean: { mean: Number(e.target.value) },
                                });

                                return {
                                    ...prev,
                                    mean: Number(e.target.value),
                                };
                            });
                        }}
                    />
                </label>
            )}
        </div>
    );
}

export default DistributionForm;

// src/components/DistributionForm.vue
<template>
  <div class="grid">
    <label for="distribution"
      >Distribution
      <select v-model="distribution" id="distribution">
        <option value="uniform">Uniforme</option>
        <option value="exponential">Exponencial</option>
        <option value="poisson">Poisson</option>
      </select>
    </label>
    <template v-if="distribution === 'uniform'">
      <label for="min"
        >Min

        <input v-model.number="limits.min" id="min" />
      </label>
      <label for="max"
        >Max

        <input v-model.number="limits.max" id="max" />
      </label>
    </template>
    <label v-else for="lambda"
      >lambda
      <input v-model.number="mean.mean" id="lambda" />
    </label>
  </div>
</template>

<script lang="ts" setup>
import { ref, watchEffect } from 'vue'

const distribution = ref<DistributionName>('exponential')
const mean = ref<{ mean: number }>({ mean: 0 })
const limits = ref<{ min: number; max: number }>({ min: 0, max: 0 })

watchEffect(() => {
  if (distribution.value === 'uniform') {
    emit('distribution', {
      name: distribution.value,
      mean: {
        a: limits.value.min,
        b: limits.value.max
      }
    })
  } else {
    emit('distribution', {
      name: distribution.value,
      mean: {
        mean: mean.value.mean
      }
    })
  }
})

const emit = defineEmits<{
  (e: 'distribution', value: DistributionData): void
}>()
</script>
